name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout out repository.
        uses: actions/checkout@v3
      - name: Compile in Docker.
        uses: addnab/docker-run-action@v3
        with:
          image: docker.io/library/alpine:latest
          options: -v ${{ github.workspace }}:/repo
          run: |
            cd /repo
            apk add gtk4.0-dev cargo libadwaita-dev
            cargo build --release
      - name: Upload built binary.
        uses: actions/upload-artifact@v3
        with:
          name: cachecache
          path: target/release/cachecache
